### ISSUE TITLE
"Listbox contents too short!" exception with custom ListWalker and fewer list elements than supported on screen

### ISSUE THREAD

**Issue by jrollins** [wardi/urwid#107]
The included example program throws the following exception if there are less elements in the list than could possibly be draw on screen given the current screen size:

  urwid.listbox.ListBoxError: Listbox contents too short!  Probably urwid's fault (please report):

The program is using a custom ListWalker that generates list widgets based on a provided list.
For instance, if the current screen can support 55 lines,

   ./list_walker_test.py 55

will not throw an exception, but 

  ./list_walker_test.py 54

will.  Any suggestions on how to work around this issue would be much appreciated.
Here's the program (for some reason github won't let me attach a .py file to this report?!?):

#!/usr/bin/python

import sys
import urwid

class DocWalker(urwid.ListWalker):
    def __init__(self, elements):
        self.docs = range(elements)
        self.ndocs = len(self.docs)
        self.focus = 0
        self.items = []

    def _get_doc(self, pos):
        if pos >= self.ndocs or pos < 0:
            return None, pos
        if pos >= len(self.items):
            self.items.append(urwid.Text(str(self.docs[pos])))
        return self.items[pos], pos
        
    def get_focus(self):
        return self._get_doc(self.focus)

    def set_focus(self, focus):
        self.focus = focus
        self._modified()

    def get_next(self, pos):
        return self._get_doc(pos + 1)

    def get_prev(self, pos):
        return self._get_doc(pos - 1)

def main(elements):
    palette = []

    def exit_on_q(input):
        if input in ('q', 'Q'):
            raise urwid.ExitMainLoop()

    listbox = urwid.ListBox(DocWalker(elements))
    view = urwid.Frame(urwid.AttrWrap(listbox, 'body'))
    loop = urwid.MainLoop(view, palette, unhandled_input=exit_on_q)
    loop.run()

if __name__=="__main__":
    main(int(sys.argv[1]))

**Comment by davidbaum** [comment]
Hey I've got the same bug, below is a traceback, from our Urwid-based log viewer.
Its position objects are triplets, if the traceback isn't clear.

`Mon Aug 10 15:56:25 2015 Traceback (most recent call last):
  File "<string>", line 320, in main
  File "/mnt/hgfs/mac/git/wekapp/tracing/viewer/core.py", line 274, in main
    self.loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 274, in run
    self.screen.run_wrapper(self._run)
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 268, in run_wrapper
    return fn()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 314, in _run
    self.draw_screen()
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 565, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1079, in render
    focus and self.focus_part == 'body')
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/decoration.py", line 225, in render
    canv = self._original_widget.render(size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/widget.py", line 141, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid/listbox.py", line 509, in render
    raise ListBoxError, "Listbox contents too short!  Probably urwid's fault (please report): %r" % ((top,middle,bottom),)
ListBoxError: Listbox contents too short!  Probably urwid's fault (please report): (
    (0, []), 
    (0, item1, 0,0,1, 1, None), 
    (0, [
        (item2, 0,1,2, 1), 
        (item3, 0,2,3, 1), 
        (item4, 0,3,4, 1), 
        (item5, 0,4,5, 1), 
        (item6, 0,5,6, 1), 
        (item7, 0,6,7, 1), 
        (item8, 0,7,8, 1), 
        (item9, 0,8,9, 1), 
        (item10, 0,9,10, 1), 
        (item11, 0,10,11, 1), 
        (item12, 0,11,12, 1), 
        (item13, 0,12,13, 1), 
        (item14, 0,13,14, 1), 
        (item15, 0,14,15, 1), 
        (item16, 0,15,16, 1), 
        (item17, 0,16,17, 1), 
        (item18, 0,17,18, 1), 
        (item19, 0,18,19, 1), 
        (item20, 0,19,20, 1), 
        (item21, 0,20,21, 1), 
        (item22, 0,21,22, 1), 
        (item23, 0,22,23, 1), 
        (item24, 0,23,24, 1), 
        (item25, 0,24,25, 1), 
        (item26, 0,25,26, 1), 
        (item27, 0,26,27, 1), 
        (item28, 0,27,28, 1), 
        (item29, 0,28,29, 1), 
        (item30, 0,29,30, 1), 
        (item31, 0,30,31, 1), 
        (item32, 0,31,32, 1), 
        (item33, 0,32,33, 1), 
        (item34, 0,33,34, 1), 
        (item35, 0,34,35, 1), 
        (item36, 0,35,36, 1), 
        (item37, 0,36,37, 1), 
        (item38, 0,37,38, 1), 
        (item39, 0,38,39, 1), 
        (item40, 0,39,40, 1), 
        (item41, 0,40,41, 1), 
        (item42, 0,41,42, 1), 
        (item43, 0,42,43, 1), 
        (item44, 0,43,44, 1), 
        (item45, 0,44,45, 1), 
        (item46, 0,45,46, 1), 
        (item47, 0,46,47, 1), 
        (item48, 0,47,48, 1), 
        (item49, 0,48,49, 1), 
        (item50, 0,49,50, 1), 
        (item51, 0,50,51, 1), 
        (item52, 0,51,52, 1), 
        (item53, 0,52,53, 1), 
        (item54, 0,53,54, 1), 
        (item55, 0,54,55, 1), 
        (item56, 0,55,56, 1), 
        (item57, 0,56,57, 1), 
        (item58, 0,57,58, 1), 
        (item59, 0,58,59, 1), 
        (item60, 0,59,60, 1), 
        (item61, 0,60,61, 1), 
        (item62, 0,61,62, 1), 
        (item63, 0,62,63, 1), 
        (item64, 0,63,64, 1), 
        (item65, 0,64,65, 1), 
        (item66, 0,65,66, 1), 
        (item67, 0,66,67, 1), 
        (item68, 0,67,68, 1), 
        (item69, 0,68,69, 1), 
        (item70, 0,69,70, 1), 
        (item71, 0,70,71, 1), 
        (item72, 0,71,72, 1), 
        (item73, 0,72,73, 1), 
        (item74, 0,73,74, 1), 
        (item75, 0,74,75, 1)
    ])
)
`

**Comment by davidbaum** [comment]
@jrollins I think you've got a bug there.
The bug is that you're returning a valid (not None) position object, for an in-valid position.
Apply the following patch to resolve it.
```@@ -12,7 +12,7 @@ class DocWalker(urwid.ListWalker):

     def _get_doc(self, pos):
         if pos >= self.ndocs or pos < 0:
-            return None, pos
+            return None, None
         if pos >= len(self.items):
             self.items.append(urwid.Text(str(self.docs[pos])))
         return self.items[pos], pos
```
