### ISSUE TITLE
urwid 1.3.0 doesn't clean up terminal on KeyboardInterrupt

### ISSUE THREAD

**Issue by dholth** [wardi/urwid#157]
Probably the bottom two lines should be changed to 

```python
    try: 
        self.event_loop.run() 
    finally: 
        self.stop()
```

(or can 'with' be used here?)

main_loop.py:L366:
```python
    def _run(self):
        try:
            self.start()
        except CantUseExternalLoop:
            try:
                return self._run_screen_event_loop()
            finally:
                self.screen.stop()

        self.event_loop.run()
        self.stop()
```

**Comment by dholth** [comment]
Appears to be fixed in revision control

**Comment by ianzhang366** [comment]
Hi @dholth 

I'm seeing this issue on my env... 

```
Traceback (most recent call last):
  File "home/Library/Python/3.9/lib/python/site-packages/urwid/main_loop.py", line 377, in _run
    self.start()
  File "home/Library/Python/3.9/lib/python/site-packages/urwid/main_loop.py", line 344, in start
    raise CantUseExternalLoop(
urwid.main_loop.CantUseExternalLoop: Screen {0!r} doesn't support external event loops

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "home/Library/Python/3.9/bin/urlscan", line 216, in <module>
    main()
  File "home/Library/Python/3.9/bin/urlscan", line 204, in main
    tui.main()
  File "home/Library/Python/3.9/lib/python/site-packages/urlscan/urlchoose.py", line 240, in main
    self.loop.run()
  File "home/Library/Python/3.9/lib/python/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "home/Library/Python/3.9/lib/python/site-packages/urwid/main_loop.py", line 380, in _run
    return self._run_screen_event_loop()
  File "home/Library/Python/3.9/lib/python/site-packages/urwid/main_loop.py", line 439, in _run_screen_event_loop
    keys, raw = self.screen.get_input(True)
  File "home/Library/Python/3.9/lib/python/site-packages/urwid/curses_display.py", line 279, in get_input
    keys, raw = self._get_input( self.max_tenths )
  File "home/Library/Python/3.9/lib/python/site-packages/urwid/curses_display.py", line 316, in _get_input
    key = self._getch(wait_tenths)
  File "home/Library/Python/3.9/lib/python/site-packages/urwid/curses_display.py", line 194, in _getch
    return self.s.getch()
KeyboardInterrupt
```

Any idea how to debug or resolve this one?
