### ISSUE TITLE
Crash defect in raw_display.py line 749

### ISSUE THREAD

**Issue by squrky** [wardi/urwid#96]
Hi,

I believe I've found a crash bug in raw_display.py on line 749. Resizing the display downwards in width and height results in IndexError in the following code:

```python
for row in r.content():
    y += 1
    if osb and osb[y] == row: # <-- Crash here
        # this row of the screen buffer matches what is
        # currently displayed, so we can skip this line
        sb.append( osb[y] )
        continue
````

Replacing the if clause logic with `y < len(osb) and osb[y] == row` seems to fix the issue for me.

**Comment by wardi** [comment]
I can't reproduce this. Could you include the full traceback?

**Comment by squrky** [comment]
Of course. I'll send a traceback and client code through early this week (I'm busy busy today). 

Thanks.

**Comment by squrky** [comment]
I managed to reproduce this in the graph example. 
```
Traceback (most recent call last):
  File "./graph.py", line 359, in <module>
    main()
  File "./graph.py", line 353, in main
    GraphController().main()
  File "./graph.py", line 337, in main
    self.loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid-1.3.1_dev-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/urwid-1.3.1_dev-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid-1.3.1_dev-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/usr/local/lib/python2.7/dist-packages/urwid-1.3.1_dev-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 706, in _loop
    self._entering_idle()
  File "/usr/local/lib/python2.7/dist-packages/urwid-1.3.1_dev-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 667, in _entering_idle
    callback()
  File "/usr/local/lib/python2.7/dist-packages/urwid-1.3.1_dev-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 560, in entering_idle
    self.draw_screen()
  File "/usr/local/lib/python2.7/dist-packages/urwid-1.3.1_dev-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 575, in draw_screen
    self.screen.draw_screen(self.screen_size, canvas)
  File "/usr/local/lib/python2.7/dist-packages/urwid-1.3.1_dev-py2.7-linux-x86_64.egg/urwid/raw_display.py", line 749, in draw_screen
    if osb and osb[y] == row:
IndexError: list index out of range
```
I launched graph.py inside xterm (Linux Mint) and drag resized the windows diagonally a few times.

Revision 875dd11555e3467ff7d9c0ab3521af1724a6bc35.

**Comment by squrky** [comment]
The above traceback was generated against an installed version of urwid. I get a crash with the same STR against revision 875dd11555e3467ff7d9c0ab3521af1724a6bc35:
```
Traceback (most recent call last):
  File "./examples/graph.py", line 361, in <module>
    main()
  File "./examples/graph.py", line 355, in main
    GraphController().main()
  File "./examples/graph.py", line 339, in main
    self.loop.run()
  File "/home/nay/dev/thirdparty/urwid/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/nay/dev/thirdparty/urwid/urwid/main_loop.py", line 379, in _run
    raise e
IndexError: list index out of range
```

**Comment by drestebon** [comment]
This issue is still there. Is there any plans to fix it? the fix from squrky does indeed work.
